jwt:
  secret: javainuse

spring:
  datasource:
    url: jdbc:mysql://localhost/jwt?autoReconnect=true&useSSL=false
    username: root
    password: root
    platform: mysql

    driver-class-name: com.mysql.jdbc.Driver
    hibernate:
      ddl-auto: create-drop
